spring:
  application:
    name: orders

  datasource:
    url: jdbc:h2:mem:orderambev;
    username: sa
    password: password
    driverClassName: org.h2.Driver
    hibernate:
      ddl-auto: create-drop
    show-sql: true
  h2:
    console:
      enabled: true
    path: /h2-console