version: "3.7"

services:

  mysql:
    image: mysql:5.7
    hostname: mysql
    container_name: miniautorizador
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: miniautorizador
      MYSQL_USER: root
      #MYSQL_PASSWORD: root
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"